---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - core.vllmoperator.org
  resources:
  - vllmdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.vllmoperator.org
  resources:
  - vllmdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - core.vllmoperator.org
  resources:
  - vllmdeployments/status
  verbs:
  - get
  - patch
  - update
